config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'articles#index'
  resources :articles
  delete '/articles/:id' => 'articles#destroy'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  # before_action :set_article, only: [:edit, :update, :show, :destroy]
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = 'Article was successfully created'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = 'Article was successfully edited'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
    @articles = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy(article_params)
      flash[:notice] = 'Article was successfully deleted'
      redirect_to articles_path
    else
      render 'index'
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h3>The following errors have prevented article to be created</h3>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @article do |f| %>
  <span>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </span> 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to "Back to Articles Listing", articles_path %>

app/views/articles/edit.html.erb
<h2>Showing editing of Articles</h2>
<%= render "form" %>

app/views/articles/index.html.erb
<h1>Showing list of all articles</h1>
<p>
  <%= link_to "Create new article", new_article_path %>
</p>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to "Edit", edit_article_path(article) %></td>
        <td><%= link_to "Show", article_path(article) %></td>
        <td><%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <%end%>
</table>

app/views/articles/new.html.erb
<h1>Create an article</h1>
<%= render "form" %>

app/views/articles/show.html.erb
<h1>Showing selected Articles</h1>

<p>
  Title: <%= @articles.title %>
</p>
<p>
  Description: <%= @articles.description %>
</p>
<button><%= link_to "Back to Articles Listing", articles_path %></button>
<button><%= link_to "Edit this article", edit_article_path(@articles) %></button>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
      <ul>
        <li><%= msg %></li>
      </ul>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    </head>
    
    <body>
    <%= render "layouts/messages" %>
    <%= yield %>
  </body>
</html>